services:
  - type: web
    name: kura
    runtime: node
    plan: starter
    buildCommand: pnpm install --frozen-lockfile
    startCommand: node --env-file=.env --import tsx dev.js
    autoDeploy: true
